version: '3.7'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - 8080:8080
        restart: on-failure
        volumes:
            - ./:/var/www:cached

